services:
  - type: web
    name: wizard-wars
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
