services:
  - type: web
    name: wizard-wars
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: warn
      - key: ADMIN_USERNAMES
        sync: false
      - key: ADMIN_PREFIX
        sync: false
