/**
 * Builds the committed in-flight fireball sprite sheet from five source PNGs.
 *
 * Source (not committed): default path points at the user's local `my-sprites`
 * vault; override with `--src-dir=<path>` or `FIREBALL_FLY_SRC_DIR`.
 *
 * Output (committed):
 *  - `public/assets/sprites/abilities/fireball-fly.png`
 *      5 east-facing frames in a horizontal strip. Each source frame is cropped
 *      to visible alpha, scaled with nearest-neighbor pixel art sampling, and
 *      centered inside a transparent 256x256 Phaser cell.
 *
 * The cast/channel sheet and ember particle are intentionally not generated by
 * this script; they are separate runtime assets and must remain unchanged.
 */

import { existsSync } from "node:fs"
import { mkdir, readdir } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"
import { pathToFileURL } from "node:url"

import sharp from "sharp"

export const DEFAULT_FIREBALL_FLY_SRC_DIR =
  "/Users/jakemcbride/Personal/Development/my-sprites/ITCHIO/FB00_nyknck/FB00_nyknck"

export const FIREBALL_FLY_FRAME_SIZE_PX = 256
export const FIREBALL_FLY_FRAME_COUNT = 5

const OUT_DIR = resolve(process.cwd(), "public/assets/sprites/abilities")
const FLY_OUT = resolve(OUT_DIR, "fireball-fly.png")

type Bounds = { left: number; top: number; width: number; height: number }

export type BuildFireballFlySheetResult = {
  outPath: string
  frameCount: number
  frameSize: number
  width: number
  height: number
}

type BuildFireballFlySheetOptions = {
  sourceDir?: string
  outPath?: string
  frameSize?: number
  log?: (message: string) => void
}

/**
 * Returns the required source filename for a one-based fireball frame number.
 *
 * @param frameNumber - One-based frame number.
 * @returns Required filename, e.g. `FB001.png`.
 */
function fireballFlyFrameName(frameNumber: number): string {
  return `FB00${frameNumber}.png`
}

/**
 * Resolves required fireball fly source frame paths in deterministic order.
 *
 * @param sourceDir - Directory containing `FB001.png` through `FB005.png`.
 * @returns Absolute source frame paths ordered by animation frame.
 */
export async function resolveFireballFlyFramePaths(
  sourceDir = DEFAULT_FIREBALL_FLY_SRC_DIR,
): Promise<string[]> {
  if (!existsSync(sourceDir)) {
    throw new Error(
      `Fireball fly source directory not found: ${sourceDir}. ` +
        "Set FIREBALL_FLY_SRC_DIR or pass --src-dir=<path>.",
    )
  }

  const entries = new Set(await readdir(sourceDir))
  const requiredNames = Array.from({ length: FIREBALL_FLY_FRAME_COUNT }, (_, i) =>
    fireballFlyFrameName(i + 1),
  )
  const missing = requiredNames.filter((name) => !entries.has(name))
  if (missing.length > 0) {
    throw new Error(
      `Fireball fly source directory ${sourceDir} missing required frames: ${missing.join(", ")}`,
    )
  }

  return requiredNames.map((name) => join(sourceDir, name))
}

/**
 * Finds the tight non-transparent bounding box of an RGBA buffer.
 *
 * @param raw - RGBA pixel buffer.
 * @param width - Buffer width in pixels.
 * @param height - Buffer height in pixels.
 * @returns Visible alpha bounds, or `null` if the frame is fully transparent.
 */
function alphaBounds(raw: Buffer, width: number, height: number): Bounds | null {
  let minX = width
  let minY = height
  let maxX = -1
  let maxY = -1

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const alpha = raw[(y * width + x) * 4 + 3]!
      if (alpha === 0) continue
      if (x < minX) minX = x
      if (x > maxX) maxX = x
      if (y < minY) minY = y
      if (y > maxY) maxY = y
    }
  }

  if (maxX < 0) return null
  return {
    left: minX,
    top: minY,
    width: maxX - minX + 1,
    height: maxY - minY + 1,
  }
}

/**
 * Renders one source PNG into a transparent square Phaser frame cell.
 *
 * @param framePath - Source PNG path.
 * @param frameSize - Output square cell size in pixels.
 * @returns PNG bytes for one 256x256 frame cell.
 */
async function renderFlyFrameCell(framePath: string, frameSize: number): Promise<Buffer> {
  const { data, info } = await sharp(framePath)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const bounds = alphaBounds(data, info.width, info.height)
  if (!bounds) {
    throw new Error(`Fireball fly source frame has no visible pixels: ${framePath}`)
  }

  return sharp(data, {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .extract(bounds)
    .resize(frameSize, frameSize, {
      fit: "contain",
      kernel: "nearest",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png({ compressionLevel: 9 })
    .toBuffer()
}

/**
 * Builds the committed fireball fly sprite sheet from ordered source frames.
 *
 * @param options - Build paths and output settings.
 * @returns Output metadata for tests and CLI logging.
 */
export async function buildFireballFlySheet(
  options: BuildFireballFlySheetOptions = {},
): Promise<BuildFireballFlySheetResult> {
  const sourceDir = options.sourceDir ?? DEFAULT_FIREBALL_FLY_SRC_DIR
  const outPath = options.outPath ?? FLY_OUT
  const frameSize = options.frameSize ?? FIREBALL_FLY_FRAME_SIZE_PX
  const log = options.log ?? console.log
  const framePaths = await resolveFireballFlyFramePaths(sourceDir)

  await mkdir(dirname(outPath), { recursive: true })

  const composites: sharp.OverlayOptions[] = []
  for (const [index, framePath] of framePaths.entries()) {
    composites.push({
      input: await renderFlyFrameCell(framePath, frameSize),
      left: index * frameSize,
      top: 0,
    })
  }

  const width = frameSize * framePaths.length
  const height = frameSize
  await sharp({
    create: {
      width,
      height,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .png({ compressionLevel: 9 })
    .toFile(outPath)

  log(`wrote ${outPath} (${framePaths.length} fly frames, ${frameSize}x${frameSize} each)`)
  return {
    outPath,
    frameCount: framePaths.length,
    frameSize,
    width,
    height,
  }
}

/**
 * Parses `--key=value` CLI arguments into a small option map.
 *
 * @param argv - CLI argument list without node/script entries.
 * @returns Parsed key/value arguments.
 */
function parseArgs(argv: readonly string[]): Record<string, string> {
  return Object.fromEntries(
    argv.flatMap((arg) => {
      const match = /^--([^=]+)=(.*)$/.exec(arg)
      return match ? [[match[1]!, match[2]!]] : []
    }),
  )
}

/**
 * Returns true when this module is executing as the CLI entrypoint.
 *
 * @param argv - Process argument vector.
 * @returns Whether `argv[1]` points at this module.
 */
function isCliEntrypoint(argv: readonly string[]): boolean {
  const scriptPath = argv[1]
  return Boolean(scriptPath && pathToFileURL(resolve(scriptPath)).href === import.meta.url)
}

/**
 * Runs the fireball fly sheet builder from CLI arguments.
 *
 * @returns Resolves after the output sheet is written.
 */
async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2))
  await buildFireballFlySheet({
    sourceDir: args["src-dir"] ?? process.env.FIREBALL_FLY_SRC_DIR,
    outPath: args.out,
  })
}

if (isCliEntrypoint(process.argv)) {
  void main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
