/**
 * Reads `public/assets/tilemaps/arena.json`, extracts axis-aligned rectangles from the
 * Tiled object layer **`PropColliders`**, and writes
 * `src/shared/balance-config/generated/arena-prop-colliders.ts`.
 *
 * Run: `bun run build:arena-colliders`
 *
 * In Tiled, add rectangle objects on **PropColliders** (width/height > 0). Point objects are skipped.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, "..")
const ARENA_JSON = resolve(ROOT, "public/assets/tilemaps/arena.json")
const OUT_FILE = resolve(ROOT, "src/shared/balance-config/generated/arena-prop-colliders.ts")

type TiledObject = {
  readonly x?: number
  readonly y?: number
  readonly width?: number
  readonly height?: number
}

type TiledLayer = {
  readonly name?: string
  readonly type?: string
  readonly objects?: readonly TiledObject[]
}

type TiledMap = {
  readonly layers?: readonly TiledLayer[]
}

function main(): void {
  const raw = readFileSync(ARENA_JSON, "utf8")
  const map = JSON.parse(raw) as TiledMap
  const layers = map.layers ?? []
  const propLayer = layers.find((l) => l.type === "objectgroup" && l.name === "PropColliders")
  const objects = propLayer?.objects ?? []

  const rects: { x: number; y: number; width: number; height: number }[] = []
  for (const obj of objects) {
    const w = obj.width ?? 0
    const h = obj.height ?? 0
    if (w <= 0 || h <= 0) continue
    rects.push({
      x: obj.x ?? 0,
      y: obj.y ?? 0,
      width: w,
      height: h,
    })
  }

  const body = `/**
 * AUTO-GENERATED by \`bun run build:arena-colliders\`. Do not edit by hand.
 * Source: public/assets/tilemaps/arena.json (object layer PropColliders).
 */
export const GENERATED_ARENA_PROP_COLLIDERS = ${JSON.stringify(rects, null, 2)} as const
`

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, body, "utf8")
  console.log(`Wrote ${rects.length} collider(s) to ${OUT_FILE}`)
}

main()
