/**
 * Reads `public/assets/tilemaps/arena.json`, extracts axis-aligned rectangles
 * from known Tiled object layers, and writes generated collider constants.
 *
 * Run: `bun run build:arena-colliders`
 *
 * In Tiled/Phaser Editor, add rectangle objects on supported object layers
 * (width/height > 0). Point objects are skipped.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, "..")
const ARENA_JSON = resolve(ROOT, "public/assets/tilemaps/arena.json")
const OUT_DIR = resolve(ROOT, "src/shared/balance-config/generated")
const COLLIDER_OUTPUTS = [
  {
    layerName: "PropColliders",
    exportName: "GENERATED_ARENA_PROP_COLLIDERS",
    fileName: "arena-prop-colliders.ts",
  },
  {
    layerName: "NonWalkableAreas",
    exportName: "GENERATED_ARENA_NON_WALKABLE_COLLIDERS",
    fileName: "arena-non-walkable-colliders.ts",
  },
] as const

type TiledObject = {
  readonly x?: number
  readonly y?: number
  readonly width?: number
  readonly height?: number
}

type TiledLayer = {
  readonly name?: string
  readonly type?: string
  readonly objects?: readonly TiledObject[]
}

type TiledMap = {
  readonly layers?: readonly TiledLayer[]
}

function readColliderRects(
  map: TiledMap,
  layerName: string,
): { x: number; y: number; width: number; height: number }[] {
  const layers = map.layers ?? []
  const layer = layers.find((l) => l.type === "objectgroup" && l.name === layerName)
  const objects = layer?.objects ?? []

  const rects: { x: number; y: number; width: number; height: number }[] = []
  for (const obj of objects) {
    const w = obj.width ?? 0
    const h = obj.height ?? 0
    if (w <= 0 || h <= 0) continue
    rects.push({
      x: obj.x ?? 0,
      y: obj.y ?? 0,
      width: w,
      height: h,
    })
  }
  return rects
}

function buildSource(
  layerName: string,
  exportName: string,
  rects: readonly { x: number; y: number; width: number; height: number }[],
): string {
  return `/**
 * AUTO-GENERATED by \`bun run build:arena-colliders\`. Do not edit by hand.
 * Source: public/assets/tilemaps/arena.json (object layer ${layerName}).
 */
export const ${exportName} = ${JSON.stringify(rects, null, 2)} as const
`
}

function main(): void {
  const raw = readFileSync(ARENA_JSON, "utf8")
  const map = JSON.parse(raw) as TiledMap

  mkdirSync(OUT_DIR, { recursive: true })

  for (const output of COLLIDER_OUTPUTS) {
    const rects = readColliderRects(map, output.layerName)
    const outFile = resolve(OUT_DIR, output.fileName)
    writeFileSync(outFile, buildSource(output.layerName, output.exportName, rects), "utf8")
    console.log(`Wrote ${rects.length} collider(s) to ${outFile}`)
  }
}

main()
